AWSTemplateFormatVersion: '2010-09-09'
Description: Template para criar uma instância EC2

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-XXXXXXXX  # Altere para a AMI desejada
      KeyName: XXXXXX              # Nome do seu par de chaves
      SecurityGroupIds:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0           # Permitir acesso SSH de qualquer IP

  return go(f, seed, [])
}
