AWSTemplateFormatVersion: '2010-09-09'
Description: Template para criar um grupo de Auto Scaling

Resources:
  MyLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      InstanceType: t2.micro
      ImageId: ami-XXXXXXXXXXXX  # Altere para a AMI desejada
      SecurityGroups:
        - !Ref MySecurityGroup

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref MyPublicSubnet
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      MinSize: 1
      MaxSize: 5
      DesiredCapacity: 2
      Tags:
        - Key: Name
          Value: MyAutoScalingGroup
          PropagateAtLaunch: true
